In [2]:
pd = require('pandas-js')
nj = require('jsnumpy')
np = require('mathjs')
plt = require('nodeplotlib')

{ plot: [Function], clear: [Function], stack: [Function: s] }

In [73]:
arrOne = [[2,1],[1,-3]]
arrTwo = [[3],[4]]
T = nj.matrixMultiply(arrOne,arrTwo)
pOne = {x: [0,3], y: [0,4]}
pTwo = {x: [0,10], y: [0, -9]}
console.log(T)

[ [ 10 ], [ -9 ] ]


In [59]:
x = [
  [1,2],
  [3,4],
  [5,6]
]
means = np.mean(x,0)
console.log('Means', means)
centered = nj.subtract(x, means)
console.log('Centered', centered)
std = np.std(x, 0, 'uncorrected')
console.log('STD', std)
stand = nj.divide(centered, std)
console.log('Standardized', stand)
trans = np.ctranspose(stand)
before = nj.matrixMultiply(trans, stand)
cov = nj.divide(before, 2)
console.log('Covariance Matrix', cov)
eig = np.eigs(np.ctranspose(cov))
values = eig.values
vectors = eig.vectors
console.log('EigValues', values)
console.log('EigVectors', nj.transpose(vectors))
p = nj.matrixMultiply(centered, nj.transpose(vectors))


Means [ 3, 4 ]
Centered [ [ -2, -2 ], [ 0, 0 ], [ 2, 2 ] ]
STD [ 1.632993161855452, 1.632993161855452 ]
Standardized [
  [ -1.224744871391589, -1.224744871391589 ],
  [ 0, 0 ],
  [ 1.224744871391589, 1.224744871391589 ]
]
Covariance Matrix [
  [ 1.4999999999999998, 1.4999999999999998 ],
  [ 1.4999999999999998, 1.4999999999999998 ]
]
EigValues [ 0, 2.9999999999999996 ]
EigVectors [
  [ 0.7071067811865476, -0.7071067811865475 ],
  [ 0.7071067811865475, 0.7071067811865476 ]
]


[
  [ -2.82842712474619, -2.220446049250313e-16 ],
  [ 0, 0 ],
  [ 2.82842712474619, 2.220446049250313e-16 ]
]

In [60]:
xs = []
ys = []
x.forEach(x => {
  xs.push(x[0])
  ys.push(x[1])
})
xp = p.map(x => x[0])
yp = p.map(x => x[1])
plt.plot([{x:xs, y:ys, mode: 'markers'}, {x:xp, y:yp, mode: 'markers'}], {height: 600, width: 600})

In [6]:
from numpy import array
from numpy import mean
from numpy import std
from numpy import cov
from numpy.linalg import eig
# define a matrix (we'll pretend that we've already separated our X and Y matrices)
X = array([[1, 2], [3, 4], [5, 6]])
print("Data: ", X)
# calculate the mean of each column
means = mean(X.T, axis=1)
print("\n Means: \n", means)
# center columns by subtracting column means
centered_data = X - means
print("\n Centered Data: \n", centered_data)
# calculate the standard deviation of each column
std_devs = std(X.T, axis=1)
testStd = std([1,3,5])
print('\n trans', X.T)
print("\n STD:", std_devs)
# complete the standardization by dividing by std_dev
standardized_data = centered_data / std_devs
print("\n Standardized Data: \n", standardized_data)
# calculate covariance matrix of centered matrix
# We're not going to find the covaraicne matrix by the (Z^T)(Z) method, I trust this function more
covariance_matrix = cov(standardized_data.T)
print("\n Covariance Matrix: \n", covariance_matrix)
# eigendecomposition of covariance matrix
values, vectors = eig(covariance_matrix)
print("\n Eigenvectors: \n", vectors)
print("\n Eigenvalues: \n", values)
# project data
P = vectors.T.dot(centered_data.T)
print("\n Projected Data: \n", P.T)

Data:  [[1 2]
 [3 4]
 [5 6]]

 Means: 
 [3. 4.]

 Centered Data: 
 [[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]

 trans [[1 3 5]
 [2 4 6]]

 STD: [1.63299316 1.63299316]

 Standardized Data: 
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]

 Covariance Matrix: 
 [[1.5 1.5]
 [1.5 1.5]]

 Eigenvectors: 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

 Eigenvalues: 
 [3. 0.]

 Projected Data: 
 [[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]
